/* Generated By:JJTree&JavaCC: Do not edit this line. CykConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CykConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WORD = 5;
  /** RegularExpression Id. */
  int SENTENCE = 6;
  /** RegularExpression Id. */
  int SYMBOL = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<WORD>",
    "<SENTENCE>",
    "<SYMBOL>",
    "\"->\"",
    "\";\"",
  };

}
