/* Generated By:JavaCC: Do not edit this line. CykTreeConstants.java Version 5.0 */
public interface CykTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTSYMBOL = 2;
  public int JJTVALUE = 3;
  public int JJTSENTENCE = 4;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "Symbol",
    "Value",
    "Sentence",
  };
}
/* JavaCC - OriginalChecksum=d0be0a6111d5c039a6b0a1fb0e6fbe6b (do not edit this line) */
